name: release

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment'
        required: true
        default: 'production'
      branch:
        description: 'Branch'
        required: true
        default: 'master'
jobs:
  release:
    name: release
    runs-on: ubuntu-18.04
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          branch: ${{ github.event.inputs.branch }}
      - name: node
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: install
        run: npm ci
      - name: release
        run: npm run release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.ADOBE_BOT_NPM_TOKEN }}
